# Generated by Django 5.0.1 on 2024-01-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pessoa_encodings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='ltima_verificacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='total_verificacoes',
            field=models.IntegerField(default=0),
        ),
    ]
