# Generated by Django 5.0.1 on 2024-01-18 02:09

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_ltima_verificacao_pessoa_ultima_verificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='ultima_verificacao',
        ),
        migrations.CreateModel(
            name='Verificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(default=datetime.datetime.now)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
            ],
        ),
    ]
