# Generated by Django 5.0.1 on 2024-01-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_pessoa_ultima_verificacao_verificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificacao',
            name='horario',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
